spring:
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
    generate-ddl: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}

    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123}
server:
  port: ${PORT:8083}